controller_manager:
  ros__parameters:
    update_rate: 100

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

left_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - left_shoul_base2shoul_joint
    - left_shoul2shoul_rot_joint
    - left_arm2armrot_joint
    - left_armrot2elbow_joint
    - left_forearm2forearmrot_joint
    - left_forearmrot2forearm_pitch_joint
    - left_forearm_pitch2forearm_roll_joint

  gains:
    left_joint1: {p: 100.0, d: 10.0, i: 1.0}
    left_joint2: {p: 100.0, d: 10.0, i: 1.0}
    left_joint3: {p: 100.0, d: 10.0, i: 1.0}
    left_joint4: {p: 100.0, d: 10.0, i: 1.0}
    left_joint5: {p: 100.0, d: 10.0, i: 1.0}
    left_joint6: {p: 100.0, d: 10.0, i: 1.0}
    left_joint7: {p: 100.0, d: 10.0, i: 1.0}

  state_publish_rate: 50
  action_monitor_rate: 10

right_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - right_shoul_base2shoul_joint
    - right_shoul2shoul_rot_joint
    - right_arm2armrot_joint
    - right_armrot2elbow_joint
    - right_forearm2forearmrot_joint
    - right_forearmrot2forearm_pitch_joint
    - right_forearm_pitch2forearm_roll_joint

  gains:
    right_joint1: {p: 100.0, d: 10.0, i: 1.0}
    right_joint2: {p: 100.0, d: 10.0, i: 1.0}
    right_joint3: {p: 100.0, d: 10.0, i: 1.0}
    right_joint4: {p: 100.0, d: 10.0, i: 1.0}
    right_joint5: {p: 100.0, d: 10.0, i: 1.0}
    right_joint6: {p: 100.0, d: 10.0, i: 1.0}
    right_joint7: {p: 100.0, d: 10.0, i: 1.0}

  state_publish_rate: 50
  action_monitor_rate: 10

